<?php


function mahasz_js_init(){
	global $user, $node;

  //user fields
  /* ez majd csak akkor kell, ha minden mezőt be kell tenni. Most csak néhány kell, amiket nem módosíthat, mégis függnekj tőle más mezők!*/
  /*
  $user_keys = array_keys( field_read_fields(array('entity_type' => 'user', 'bundle' => 'user'))  );
  foreach($user_keys as $key) {
    print_r( $key );
    $field = field_get_items('user', $user, $key);
    print_r( $field );
  }
  */


  /* make object dummy simple */
  function simpler($arr) {
    global $i;
    //print " START($i) "; 
    if($i > 18){
      //print " törés "; 
      return $arr;
    }
    if(is_array($arr) && sizeof($arr) == 1){ 
      //print " array,size=1 ";
      $i++;
      return simpler(array_pop($arr));
    }
    return $arr;
  }


  /* array of an object*/
  function mahasz_field($name, $type){
    global $$type;
    $my_type = ($type == 'user') ? user_load($$type->uid) : $$type;
    return simpler(field_get_items($type, $my_type, $name));
  }

  /* several fields from same type */
  function mahasz_fields($names, $type) {
    $names = is_array($names) ? $names : array($names);
    $fields = array();
    foreach ($names as $name) {
      $fields += array($name => mahasz_field($name, $type));
    }
    return $fields;
  }

	//build args dynamically
	$args = array();
	for($i = 0; $a = arg($i); $i++){
		$args[] = $a;
		if ($i>20) {
			watchdog('mahasz_js', 'infinite loop!', array(), WATCHDOG_CRITICAL);
			break;
		}
	}

	$node = menu_get_object();

	drupal_add_js(array(
		'mahasz_js' => array( 
			'args' => $args,
			'currentUser' => $user->uid,
      'user_fields' => !$user->uid > 0 ? array() : 
        mahasz_fields(array('field_regisztralo_szemelye', 'field_email', 'field_teljes_nev', 'field_cegnev'), 'user'),
      'nid' => !empty($node) ? $node->nid : '',
      'uid' => !empty($node) ? $node->uid : '',
      'node_type' => !empty($node) ? $node->type : '',
			'node_fields' => !empty($node) ? array(
        'field_jogositas' => field_get_items('node', $node, 'field_jogositas'),
        'field_jogositas_2014' => field_get_items('node', $node, 'field_jogositas_2014'),
        'field_jogositas_2015' => field_get_items('node', $node, 'field_jogositas_2015'),
        'field_jogositas_2016' => field_get_items('node', $node, 'field_jogositas_2016'),
        'field_jogositas_2017' => field_get_items('node', $node, 'field_jogositas_2017'),
        'field_jogositas_2018' => field_get_items('node', $node, 'field_jogositas_2018'),
        'field_jogositas_2019' => field_get_items('node', $node, 'field_jogositas_2019'),
        'field_jogositas_2020' => field_get_items('node', $node, 'field_jogositas_2020')
      ) : array(),
      'formIds' => array()
		),
	), 'setting');
}

/* no logic needed for ZG modify page */
function mahasz_js_form_alter(&$form, $form_state, $form_id) {

	drupal_add_js(array(
		'mahasz_js' => array( 
			'formIds' => array($form_id),
		)
	), 'setting');
}


/**
 * Implements hook_page_build().
 */
function mahasz_js_page_build(&$page) {
  $path = drupal_get_path('module', 'mahasz_js');
  @$page['page_bottom']['mahasz_js'] = array(
    '#attached' => array(),
  );
  @$attached = &$page['page_bottom']['mahasz_js']['#attached'];
  $every_page = array('every_page' => TRUE);
  $attached['js'][$path . '/add_zg.js'] = $every_page;
  $attached['js'][$path . '/edit_node.js'] = $every_page;
  $attached['js'][$path . '/login_page.js'] = $every_page;
  $attached['js'][$path . '/sablon_szovegek.js'] = $every_page;
  $attached['js'][$path . '/password_reset.js'] = $every_page;
  $attached['js'][$path . '/levelkuldes.js'] = $every_page;
  $attached['js'][$path . '/regform.js'] = $every_page;
}


/**
 * Custom title generation for Zenegep
 */
function mahasz_custom_title($node) {
  $fields = array(
    'field_jogositas_2020',
    'field_jogositas_2019',
    'field_jogositas_2018',
    'field_jogositas_2017',
    'field_jogositas_2016',
    'field_jogositas_2015',
    'field_jogositas_2014',
    'field_jogositas'
  );

  foreach ($fields as $field){
    $elem = field_get_items('node', $node, $field);
    $elem = field_view_value('node', $node, $field, $elem[0]);
    if(!empty($elem['#markup']) && $elem['#markup'] !== 'nincs') {
      return $elem['#markup'];
    }
  }
}

function mahasz_year() {
    return date('Y');
}


?>