<?php


function mahasz_js_init(){
	global $user, $node;

  //user fields
  /* ez majd csak akkor kell, ha minden mezőt be kell tenni. Most csak néhány kell, amiket nem módosíthat, mégis függnekj tőle más mezők!*/
  /*
  $user_keys = array_keys( field_read_fields(array('entity_type' => 'user', 'bundle' => 'user'))  );
  foreach($user_keys as $key) {
    print_r( $key );
    $field = field_get_items('user', $user, $key);
    print_r( $field );
  }
  */


  /* array of an object*/
  function mahasz_field($name, $type){
    return field_get_items($type, $$type, $name);
  }

  /* several fields from same type */
  function mahasz_fields($names, $type) {
    $names = is_array($names) ? $names : array($names);
    $fields = array;
    foreach ($names as $name) {
      $fields += array($name => mahasz_field($name, $type));
    }
    return $fields;
  }

	//build args dynamically
	$args = array();
	for($i = 0; $a = arg($i); $i++){
		$args[] = $a;
		if ($i>20) {
			watchdog('mahasz_js', 'infinite loop!', array(), WATCHDOG_CRITICAL);
			break;
		}
	}

	$node = menu_get_object();
  watchdog('mahasz_js', 'user:'.print_r($user,1), array(), WATCHDOG_CRITICAL);

	drupal_add_js(array(
		'mahasz_js' => array( 
			'args' => $args,
			'currentUser' => $user->uid,
      'user' => !$user->uid > 0 ? array() : 
        mahasz_fields('field_jogi_csoport', 'user'),
      'nid' => !empty($node) ? $node->nid : '',
      'uid' => !empty($node) ? $node->uid : '',
      'node_type' => !empty($node) ? $node->type : '',
			'node_fields' => !empty($node) ? array('field_jogositas' => field_get_items('node', $node, 'field_jogositas')) : array(),
      'formIds' => array()
		),
	), 'setting');
}

/* no logic needed for ZG modify page */
function mahasz_js_form_alter(&$form, $form_state, $form_id) {

	drupal_add_js(array(
		'mahasz_js' => array( 
			'formIds' => array($form_id),
		)
	), 'setting');
}


/**
 * Implements hook_page_build().
 */
function mahasz_js_page_build(&$page) {
  $path = drupal_get_path('module', 'mahasz_js');

  $page['page_bottom']['mahasz_js'] = array(
    '#attached' => array(),
  );
  $attached = &$page['page_bottom']['mahasz_js']['#attached'];
  $every_page = array('every_page' => TRUE);
  $attached['js'][$path . '/add_zg.js'] = $every_page;
  $attached['js'][$path . '/edit_node.js'] = $every_page;
  $attached['js'][$path . '/login_page.js'] = $every_page;
  $attached['js'][$path . '/sablon_szovegek.js'] = $every_page;
  $attached['js'][$path . '/password_reset.js'] = $every_page;
  $attached['js'][$path . '/levelkuldes.js'] = $every_page;
  $attached['js'][$path . '/regform.js'] = $every_page;
}


?>